# GitHub presets
safe: true
lsi: false

# custom settings
author: Matt Ross
author_email: matt@mattross.io
description: making web stuff
destination: ./_site
exclude:
  - CNAME
  - Gruntfile.js
  - README.md
  - bower.json
  - docker-compose.yml
  - node_modules
  - package-lock.json
  - package.json
  - vendor
hightlighter: rouge
keys:
  ga: UA-19230806-1
name: mattross.io
paginate: 5
permalink: pretty
source: .
timezone: America/New_York
url: http://www.mattross.io
gems:
  - jekyll-sitemap
  - jekyll-paginate
