# GitHub presets
safe: true
lsi: false

# custom settings
author: Matt Ross
author_email: matt@mattross.io
description: making web stuff
destination: ./_site
exclude: [package.json, Gruntfile.js, node_modules]
name: mattross.io
paginate: 3
permalink: pretty
source: .
url: http://www.mattross.io/
